# coding: utf-8

"""
    The Blue Alliance API v3

    # Overview    Information and statistics about FIRST Robotics Competition teams and events. If you are looking for the old version (v2) of the API, documentation can be found [here](/apidocs/v2).   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.

    OpenAPI spec version: 3.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EventInsights2017(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'qual': 'EventInsights2017Detail',
        'playoff': 'EventInsights2017Detail'
    }

    attribute_map = {
        'qual': 'qual',
        'playoff': 'playoff'
    }

    def __init__(self, qual=None, playoff=None):
        """
        EventInsights2017 - a model defined in Swagger
        """

        self._qual = None
        self._playoff = None

        if qual is not None:
          self.qual = qual
        if playoff is not None:
          self.playoff = playoff

    @property
    def qual(self):
        """
        Gets the qual of this EventInsights2017.

        :return: The qual of this EventInsights2017.
        :rtype: EventInsights2017Detail
        """
        return self._qual

    @qual.setter
    def qual(self, qual):
        """
        Sets the qual of this EventInsights2017.

        :param qual: The qual of this EventInsights2017.
        :type: EventInsights2017Detail
        """

        self._qual = qual

    @property
    def playoff(self):
        """
        Gets the playoff of this EventInsights2017.

        :return: The playoff of this EventInsights2017.
        :rtype: EventInsights2017Detail
        """
        return self._playoff

    @playoff.setter
    def playoff(self, playoff):
        """
        Sets the playoff of this EventInsights2017.

        :param playoff: The playoff of this EventInsights2017.
        :type: EventInsights2017Detail
        """

        self._playoff = playoff

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EventInsights2017):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
