# coding: utf-8

"""
    The Blue Alliance API v3

    # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.

    OpenAPI spec version: 3.02.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .api_status import APIStatus
from .api_status_app_version import APIStatusAppVersion
from .award import Award
from .award_recipient import AwardRecipient
from .district_list import DistrictList
from .district_ranking import DistrictRanking
from .district_ranking_event_points import DistrictRankingEventPoints
from .elimination_alliance import EliminationAlliance
from .elimination_alliance_backup import EliminationAllianceBackup
from .elimination_alliance_status import EliminationAllianceStatus
from .event import Event
from .event_district_points import EventDistrictPoints
from .event_district_points_points import EventDistrictPointsPoints
from .event_district_points_tiebreakers import EventDistrictPointsTiebreakers
from .event_insights_2016 import EventInsights2016
from .event_insights_2016_detail import EventInsights2016Detail
from .event_insights_2017 import EventInsights2017
from .event_insights_2017_detail import EventInsights2017Detail
from .event_op_rs import EventOPRs
from .event_predictions import EventPredictions
from .event_ranking import EventRanking
from .event_ranking_extra_stats_info import EventRankingExtraStatsInfo
from .event_ranking_rankings import EventRankingRankings
from .event_ranking_sort_order_info import EventRankingSortOrderInfo
from .event_simple import EventSimple
from .match import Match
from .match_alliance import MatchAlliance
from .match_score_breakdown_2015 import MatchScoreBreakdown2015
from .match_score_breakdown_2015_alliance import MatchScoreBreakdown2015Alliance
from .match_score_breakdown_2016 import MatchScoreBreakdown2016
from .match_score_breakdown_2016_alliance import MatchScoreBreakdown2016Alliance
from .match_score_breakdown_2017 import MatchScoreBreakdown2017
from .match_score_breakdown_2017_alliance import MatchScoreBreakdown2017Alliance
from .match_score_breakdown_2018 import MatchScoreBreakdown2018
from .match_score_breakdown_2018_alliance import MatchScoreBreakdown2018Alliance
from .match_simple import MatchSimple
from .match_simple_alliances import MatchSimpleAlliances
from .match_videos import MatchVideos
from .media import Media
from .team import Team
from .team_event_status import TeamEventStatus
from .team_event_status_alliance import TeamEventStatusAlliance
from .team_event_status_alliance_backup import TeamEventStatusAllianceBackup
from .team_event_status_playoff import TeamEventStatusPlayoff
from .team_event_status_rank import TeamEventStatusRank
from .team_event_status_rank_ranking import TeamEventStatusRankRanking
from .team_event_status_rank_sort_order_info import TeamEventStatusRankSortOrderInfo
from .team_robot import TeamRobot
from .team_simple import TeamSimple
from .wlt_record import WLTRecord
from .webcast import Webcast
